### PR TITLE
apply `crontab filepath` command

### PR DESCRIPTION
**Pull request by 4irik**
Hello!

Crontab utility truncates the file path to 100 characters.

### CODE REVIEW

**Comment by 4irik** [comment]
see http://serverfault.com/questions/624580/crontab-truncates-file-path

**Comment by pastuhov** [comment]
+1

**Comment by klimov-paul** [comment]
> Crontab utility truncates the file path to 100 characters.

Unable to reproduce on CentOS. Sounds like an Ubuntu specific bug.

**Comment by pastuhov** [comment]
Reproduced at Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)

**Comment by klimov-paul** [comment]
Any way fix is acceptable, issue resolved by commit 8daec5e9fb2bd50d056aa0987a8df49b6c11beed

**Pull request closed without merging**
